microsoft/FFmpegInterop

FFmpegInterop/Source/MediaSampleProvider.cpp, FFmpegInterop/Source/UncompressedVideoSampleProvider.cpp
When decoding DivX video (and VC1 etc), m_pAvFrame->pkt_pts contains AV_NOPTS_VALUE right after complete frame decoding. The reason why it still works at the moment is the extra timestamp correction logic in MediaSampleProvider that simply use the dts,
av_frame_get_best_effort_timestamp() seems to correctly return the right pts in my tests. With this correction, I no longer have to correct the pts in MediaSampleProvider as well. Could you please verify with your media files and let us know if you have any issue?
=> Fix timestamp correction

FFmpegInterop/Source/UncompressedAudioSampleProvider.cpp
Hi, 
as I said in this thread https://github.com/Microsoft/FFmpegInterop/issues/24, I encountered an issue while playing dvd_pcm streams. Two of the files I provide in this folder http://1drv.ms/1fmUZxd exhibit this issue on their pcm stream (the default one) : the dts sparks vob and vts_04_04 vob. 
It looks like av_samples_alloc return value can not reliably be used to get the resampled data range. Instead, my change relies on swr_convert return value to get it.
=> Fixing wrong pcm frame length to match the actual number of samples

FFmpegInterop/Source/FFmpegInteropMSS.cpp
Hi,
I encountered issues when playing aac adts compressed samples. Samples having this format can be found in mpeg transport streams (ex: h264+aac) or Shoutcast streams (aac). 
For your convenience, here is a Shoutcast streaming aac found on shoutcast.com : http://5.39.82.140:8144
=> Aac ADTS compressed samples fix

BuildFFmpeg.bat
This pull request fixes the cl.exe not found error when building ffmpeg for winrt with newer versions of msys. We need to call set MSYS2_PATH_TYPE=inherit from BuildFFmpeg.bat since the script directly launches bash.exe.
This PR fixes issues:
https://github.com/Microsoft/FFmpegInterop/issues/64
https://github.com/Microsoft/FFmpegInterop/issues/60
https://github.com/Microsoft/FFmpegInterop/issues/40
https://github.com/Microsoft/FFmpegInterop/issues/49
=> export full current PATH from environment into MSYS2

FFmpegInterop/Source/MediaSampleProvider.cpp, FFmpegInterop/Source/UncompressedSampleProvider.cpp
When more than a single frame is part of a single compressed audio packet.
We push the packet back onto our queue, but remove the reference to it since
we processed part of it. The next time we try to use the partial packet, it
has been freed. Keep the reference on the packet when pushing it back to the
queue.
Also fix the timestamp for these packets. The frame might not have a pts
value, so keep the one from the packet.
Addresses issues #99 and #103
=> Fixing crashing issue when multiple frames are in one audio packet.

FFmpegInterop/Source/FFmpegInteropMSS.cpp, FFmpegInterop/Source/MediaSampleProvider.cpp, FFmpegInterop/Source/MediaSampleProvider.h, FFmpegInterop/Source/UncompressedAudioSampleProvider.cpp, FFmpegInterop/Source/UncompressedSampleProvider.cpp, FFmpegInterop/Source/UncompressedSampleProvider.h, FFmpegInterop/Source/UncompressedVideoSampleProvider.cpp
Since we always use an audio converter when having FFmpeg decode audio. The audio stream descriptor should specify the audio sample size as 16 bit since that's the format that we'll feed to the media pipeline.
=> Fix 24-bit decoded audio

FFmpegInterop/Source/FFmpegInteropMSS.cpp
There seems to be a memory leak once you don't release the stream in destructor. This should fix that.
=> Add releasing of the stream in destructor

BuildFFmpeg.bat, FFmpegConfig.sh
The current FFMPEG wiki documents have an out of date description on how to build the FFMPEG libraries.  For those people whom want to have a build of the FFMPEG libraries for Windows 7 desktop, the Microsoft maintained FFmpegInterop project is a great place to go since there are well written build scripts here.  We just add support for Windows 7 desktop builds.
=> Allow the FFMPEG raw libraries to be built for Windows 7 desktop

FFmpegInterop/Source/FFmpegInteropMSS.cpp, FFmpegInterop/Source/FFmpegInteropMSS.h
videos recorded with smartphone camera in portrait mode rotate the output at an angle (usually 90 degrees). FFMPEG interop does not take this into account.
Added bonus: fix for thread race between destructor and sample request.
=> Fix video orientation & thread racing

FFmpegInterop/Source/UncompressedAudioSampleProvider.cpp, FFmpegInterop/Source/UncompressedSampleProvider.cpp, FFmpegInterop/Source/UncompressedVideoSampleProvider.cpp
Frames allocated with av_frame_alloc need to be freed with av_frame_free
Thanks to @mcosmin222 for finding the issue. Issue #142
=> Fixing memory leak in uncompressed audio and video processing.

FFmpegInterop/Source/FFmpegInteropLogging.cpp, FFmpegInterop/Source/FFmpegInteropLogging.h, FFmpegInterop/Source/ILogProvider.h, FFmpegInterop/Win10/FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/Win10/FFmpegInterop/FFmpegInterop.vcxproj.filters, FFmpegInterop/Win8.1/FFmpegInterop.Shared/FFmpegInterop.Shared.vcxitems, FFmpegInterop/Win8.1/FFmpegInterop.Shared/FFmpegInterop.Shared.vcxitems.filters, Samples/SamplesWin10/MediaPlayerCPP/App.xaml.cpp, Samples/SamplesWin10/MediaPlayerCPP/App.xaml.h, Samples/SamplesWin10/MediaPlayerCS/App.xaml.cs, Samples/SamplesWin8.1/MediaPlayerCPP/MediaPlayerCPP.Shared/App.xaml.cpp, Samples/SamplesWin8.1/MediaPlayerCPP/MediaPlayerCPP.Shared/App.xaml.h, Samples/SamplesWin8.1/MediaPlayerCS/MediaPlayerCS.Shared/App.xaml.cs
This change adds plumbing on the WinRT side for the logging capabilities inside of FFmpeg.  This was invaluable for me recently while I was diagnosing an implementation I was working on, and it seemed too useful not to share.  It also includes sample implementations for C++ and CS sample projects for both UWP and Windows/WindowsPhone 8.1.
=> Logging plumbing

FFmpegInterop/Source/FFmpegInteropMSS.cpp, FFmpegInterop/Source/FFmpegInteropMSS.h
This change extends CreateFFmpegInteropMSSFromStream to have the option of taking in an empty MSS instead of initializing its own.
=> Extend CreateFFmpegInteropMSSFromStream to take empty MSS

FFmpegInterop/Source/FFmpegInteropMSS.cpp
Some files have an initial timestamp of 0 or -1, which means av_seek_frame will seek to the second timestamp instead of the first when just starting a file. This is especially noticeable for a file like http://xahlee.info/js/i/s/test.oga.
Adding the AVSEEK_FLAG_BACKWARD flag to av_seek_frame results in better behavior for this case.
=> added AVSEEK_FLAG_BACKWARD flag to av_seek_frame, also see issue #151

FFmpegInterop/Source/MediaSampleProvider.cpp, FFmpegInterop/Source/MediaSampleProvider.h
A rawstream will not have timestamps in samples, so keep a running value based on the duration of samples.
=> Fixing playback of raw streams.

FFmpegInterop/Source/MediaSampleProvider.cpp, FFmpegInterop/Source/MediaSampleProvider.h, FFmpegInterop/Source/UncompressedAudioSampleProvider.cpp
I do the skipping of broken packets at a higher level in GetNextPacket. This makes it work automatically for all sample providers. So there is no need to implement it explicitly in each provider (which can be easily forgotten when new providers are added).
Second, once the threshold has been reached, the stream will be flushed and stopped (m_isEnabled = false). This prevents FFmpegReader from pushing new packets into the queue.
=> Skip broken packages - different approach

FFmpegInterop/Win10/FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/Win8.1/FFmpegInterop.Windows/FFmpegInterop.Windows.vcxproj, FFmpegInterop/Win8.1/FFmpegInterop.WindowsPhone/FFmpegInterop.WindowsPhone.vcxproj
Currently, the interop projects references files relative to the solution directory. While this works well for the included projects and sample, it creates problems when people try to directly include the FFmpegInterop project into their own app solutions. Suddenly, include files and lib files are not found anymore. 
This PR changes the reference paths, so they look relative to the project dir. Now files are found, no matter which solution the FFmpegInterop project is referenced from.
=> Reference files relative to project directory

FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/MediaSampleProvider.cpp
The current sample presentation time stamp logic forces the first sample for all streams to be at time 0. This causes synchronization issues when streams don't start at the same time. For example, the first sample for a subtitle stream may not have the same timestamp as the first sample for the audio stream and forcing both streams to start at time 0 causes all of the subtitles to be out of sync with the audio.
This change addresses this issue by using AVFormatContext::start_time as the stream start offset when calculating sample presentation time stamps.
=> Fix stream start offset logic

FFmpegInterop/FFmpegInterop.vcxproj
This change sets the [Profile](https://docs.microsoft.com/en-us/cpp/build/reference/profile-performance-tools-profiler?view=vs-2019) linker option for release builds.
=> MSFT: 24831362 - Web Media Extensions does not build "Vulcan ready"

FFmpegInterop/FFmpegInteropMSS.cpp
In FFmpegInteropMSS::OnStarting() we have a sanity check to verify that the seek time doesn’t exceed the duration. However, the duration is start-time-based while the seek time is zero-based  having already taken into account the start time offset. This can cause the check to incorrectly fail when the start time is not zero.
For example it's possible for a file’s start time to be larger than its duration. In this case the validation check will always fail since the seek time will always be greater than the duration.
This change moves the validation check prior to adjusting the seek time by the start time offset (i.e. when seek time is start-time-based like the duration).
=> Seek time validation check incorrectly failing for file with large start time offset

FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/FFmpegInteropLogging.cpp, FFmpegInterop/FFmpegInteropLogging.h, FFmpegInterop/FFmpegInteropMSS.cpp, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj
This change updates Nuget package references to be absolute paths instead of relative paths.
Miscellaneous changes also included:
- Added SAL annotations to functions in FFmpegInteropLogging
- Updated local variable names in FFmpegInteropMSS:InitFFmpegContext() in order not to clash with local variable of same name from outer scope
=> Update Nuget package references to be absolute paths

FFmpegInterop/BitstreamReader.cpp, FFmpegInterop/BitstreamReader.h, FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/FLACSampleProvider.cpp, FFmpegInterop/FLACSampleProvider.h
When FFmpeg is built without the FLAC decoder, some fields (e.g. channels, sample rate, bit rate) may not be set on the stream's codec parameters which can cause playback to fail.
This change updates the FLACSampleProvider to parse the FLAC stream info in the codec private data and set the stream's codec parameters accordingly.
=> Set codec parameters from FLAC stream info in FLACSampleProvider

FFmpegInterop/SampleProvider.cpp
For deselected streams we set AVStream::discard to AVDISCARD_ALL. However, read_frame_internal() only honors this flag and discard packets when parsing is needed (AVStream::need_parsing && AVStream::parser). It's unclear to me whether this is a bug or the desired behavior. In any case, this violates the assertion in SampleProvider::QueuePacket() that we don't queue packets for deselected streams.
I changed the assertion in SampleProvider::QueuePacket() to a hard check so that we don't unnecessarily buffer packets for deselected streams.
=> Don't buffer packets for deselected streams

FFmpegConfig.sh
This change updates FFmpegConfig.sh to build FFmpeg with the [/PROFILE linker option](https://docs.microsoft.com/en-us/cpp/build/reference/profile-performance-tools-profiler?view=msvc-160) set. This is required for Microsoft's APIscan tool.
=> Use /PROFILE linker option for building FFmpeg binaries

FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/FFmpegInteropMSS.h
This change adds a [MediaStreamSource.Closed](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediastreamsource.closed) event handler to the FFmpegInteropMSS. This enables us to free resources as soon as possible instead of waiting until destruction.
=> MSFT: 31595456 - Add MediaStreamSource.Closed event handler

FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/FFmpegInteropMSS.h, FFmpegInterop/pch.h
The platform's IMediaStreamSourceFactory implementation will throw an error in its factory methods if a valid IMediaStreamDescriptor is not provided.
This change works around this issue by using IActivationFactory::ActivateInstance() to activate an MSS without a valid IMediaStreamDescriptor.
=> Fix activation of MSS with no stream descriptors

FFmpegInterop/FFmpegInterop.vcxproj, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj
WinDbgX has limited support for PDBs generated using the /DEBUG:FASTLINK linker option which is the default in VS2017+. For example, wild card symbol searches (x FFmpegInterop!*FFmpegInteropMSS::OnStarting) don't work.
This change updates debug builds to use the /DEBUG:FULL linker option for a better WinDbgX debugging experience.
[/DEBUG (Generate Debug Info) | Microsoft Docs](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info)
=> MSFT: 32158630 - Update debug builds to use /DEBUG:FULL linker option for better WinDbg debugging experience

FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/pch.h, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCS/MediaPlayerCS.csproj, Tests/UnitTest.csproj
This change updates FFmpegInteropMSS to be [version adaptive ](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-code) and lowers all of the projects' minimum supported version.
=> MSFT: 26268644 - Add version adaptive logic and lower min supported version

FFmpegInterop/UncompressedAudioSampleProvider.cpp, FFmpegInterop/UncompressedAudioSampleProvider.h, FFmpegInterop/pch.h
This change updates UncompressedAudioSampleProvider to handle dynamic audio format changes.
The format change is handled internally by reconfiguring the resampler so that the media type exposed to the MSS does not change.
=> MSFT: 31464795 - Handle dynamic audio format changes in UncompressedAudioSampleProvider

.gitmodules
The [Git protocol is no longer supported](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
This change switches the FFmpeg submodule URL protocol from git to https.
=> MSFT: 39125269 - Switch FFmpeg submodule URL protocol from git to https

FFmpegConfig.sh, FFmpegInterop/FFmpegInterop.vcxproj, SetupFFmpegBuildEnvironment.ps1
- Add SetupFFmpegBuildEnvironment.ps1, a script to set up the FFmpeg build environment
- Address [BA2008.EnableControlFlowGuard](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2008EnableControlFlowGuard) BinSkim errors by building FFmpeg and FFmpegInterop binaries with CFG ([/guard:cf (compiler)](https://learn.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-170), [/GUARD:CF (linker)](https://learn.microsoft.com/en-us/cpp/build/reference/guard-enable-guard-checks?view=msvc-170)) enabled
=> MSFT: 43292862, 43115907 - Add script to setup FFmpeg build environment

.gitmodules, FFmpegInterop/ACMSampleProvider.cpp, FFmpegInterop/FFmpegInteropBuffer.cpp, FFmpegInterop/FFmpegInteropBuffer.h, FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/FLACSampleProvider.cpp, FFmpegInterop/SampleProvider.cpp, FFmpegInterop/StreamFactory.cpp, FFmpegInterop/UncompressedAudioSampleProvider.cpp, FFmpegInterop/UncompressedAudioSampleProvider.h, FFmpegInterop/UncompressedSampleProvider.cpp, FFmpegInterop/UncompressedVideoSampleProvider.cpp, FFmpegInterop/Utility.h, FFmpegInterop/pch.h, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj
We're updating to the latest version of FFmpeg.
This change updates FFmpeg to [6.0](https://github.com/FFmpeg/FFmpeg/releases/tag/n6.0).
- Playback in MediaPlayerCPP
- Ogg
- MKV
- Playback in Media Player with WME
- Ogg
- MKV with Vorbis/Theora 
- Ogg properties in File Explorer with WME
=> MSFT: 39125187 - Update FFmpeg to 6.0

FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/FFmpegInteropLogging.cpp, FFmpegInterop/FFmpegInteropLogging.h, FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/H264SampleProvider.cpp, FFmpegInterop/HEVCSampleProvider.cpp, FFmpegInterop/Reader.cpp, FFmpegInterop/SampleProvider.cpp, FFmpegInterop/StreamFactory.cpp, FFmpegInterop/SubtitleSampleProvider.cpp, FFmpegInterop/Tracing.cpp, FFmpegInterop/Tracing.h, FFmpegInterop/UncompressedAudioSampleProvider.cpp, FFmpegInterop/UncompressedSampleProvider.cpp, FFmpegInterop/UncompressedVideoSampleProvider.cpp, FFmpegInterop/Utility.h, FFmpegInterop/packages.config, FFmpegInterop/pch.h, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/Package.appxmanifest, Samples/MediaPlayerCPP/packages.config, Samples/MediaPlayerCS/App.xaml.cs, Samples/MediaPlayerCS/Package.appxmanifest, Tests/UnitTest.csproj
We want to improve tracing to get better diagnostics for future bug investigations.
- Update packages
- Update to C++ 20
- Switch to using WIL's TraceLogging helpers for tracing now that they're public
- Add a custom trace macro that wraps wil::TraceLoggingProvider::TraceLoggingInfo() to provide printf-style logging with a prefix that includes file, line, function, and "this" (if it exists)
I validated Ogg playback in:
- MediaPlayerCPP
- MediaPlayerCS
- Media Player with WME
I verified that trace logging and FFmpegInteropLogging work as expected.
=> MSFT: 46989616 - Use WIL's TraceLogging helpers for tracing

.gitmodules, FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/SampleProvider.cpp, FFmpegInterop/UncompressedVideoSampleProvider.cpp, FFmpegInterop/packages.config, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/packages.config
We're updating to the latest version of FFmpeg.
- Updated to FFmpeg [6.1.1](https://github.com/FFmpeg/FFmpeg/releases/tag/n6.1.1)
- av_stream_get_side_data() was deprecated. Use av_packet_side_data_get() with AVStream::codecpar.coded_side_data instead.
- AVFrame::interlaced_frame/AVFrame::top_field_first were deprecated. Use AVFrame::flags with AV_FRAME_FLAG_INTERLACED/AV_FRAME_FLAG_TOP_FIELD_FIRST instead.
- Updated packages to the latest versions
- Playback in MediaPlayerCPP
- Ogg
- MKV
- Playback in Media Player with WME
- Ogg
- MKV with Vorbis/Theora
- Ogg properties in File Explorer with WME
=> MSFT: 47925856 - Update to FFmpeg 6.1.1

FFmpegInterop/FFmpegInterop.vcxproj, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj.filters
We want to reduce FFmpegInterop's storage footprint.
- Enable compiler and linker optimizations for favoring small code size
- Remove unnecessary dependencies on avdevice and avfilter
- Ogg playback in MediaPlayerCPP
- Ogg playback in Media Player with WME
- Ogg properties in File Explorer with WME
=> MSFT: 49309119 - Reduce FFmpegInterop's storage footprint

.gitignore, FFmpegInterop/FFmpegInteropBuffer.cpp, FFmpegInterop/FFmpegInteropBuffer.h
There is a memory leak due to FFmpegInteropBuffer not properly capturing the smart pointer for its underlying buffer in the unique_ptr deleter lambdas, which causes the underlying buffer to not be deallocated when FFmpegInteropBuffer is destroyed.
Updated FFmpegInteropBuffer to properly move capture the smart pointer for its underlying buffer in the unique_ptr deleter lambdas, so that the underlying buffer is deallocated when FFmpegInteropBuffer is destroyed.
I verified under a debugger that the underlying buffer is now being deallocated when FFmpegInteropBuffer is destroyed and memory usage is stable for Ogg playback in Media Player with in-proc WME.
=> MSFT: 49847737 - FFmpegInteropBuffer is leaking its underlying buffer

FFmpegInterop/FFmpegInteropByteStreamHandler.cpp, FFmpegInterop/FFmpegInteropByteStreamHandler.h
FFmpegInteropByteStreamHandler is closing the byte stream on failure which prevents the source resolver from rolling over and attempting other byte stream handlers when the MF_RESOLUTION_CONTENT_DOES_NOT_HAVE_TO_MATCH_EXTENSION_OR_MIME_TYPE flag is set for source resolution.
I added ByteStreamProxy which can be used to wrap a byte stream and prevent it from being closed unless permitted. It forwards all IMFByteStream calls to the underlying byte stream.
FFmpegInteropByteStreamHandler::CreateMediaSource() uses ByteStreamProxy to wrap the byte stream provided to FFmpegInteropByteStreamHandler::BeginCreateObject() and prevent it from being closed unless the MSS is successfully created and initialized, after which the byte stream will be allowed to close when the media source shuts down.
With …
=> MSFT: 50055829 - FFmpegInteropByteStreamHandler is closing the byte stream on failure preventing source resolver rollover

FFmpegInterop/FFmpegInteropLogging.cpp, FFmpegInterop/dllmain.cpp
FFmpegInterop.dll registers a custom FFmpeg logging callback, FmpegInteropLogging::Log(), on DLL load. However, this is not safe to do in scenarios that have multiple DLLs using FFmpeg due to the following race condition:
- FFmpegInterop.dll is loaded and registers its custom FFmpeg logging callback, FmpegInteropLogging::Log().
- OtherModule.dll, which also uses FFmpeg, is also loaded in the same process.
- FFmpegInterop.dll is unloaded and [av_log_callback](https://github.com/search?q=repo%3AFFmpeg%2FFFmpeg+av_log_callback&type=code) becomes a dangling pointer.
- OtherModule.dll is still loaded and using FFmpeg. FFmpeg attempts to invoke the now invalid logging callback, resulting in undefined behavior.
Even if the default logging callback was restored on DLL unload, since there is no …
=> MSFT: 49931784 - Disable FFmpeg logging in release builds

FFmpegInterop/UncompressedVideoSampleProvider.cpp
When the MF quality manager enables drop mode on a video stream, the MF stream begins dropping non-keyframes. UncompressedVideoSampleProvider is not marking any samples as keyframes, which results in the MF stream repeatedly requesting and dropping samples until EOS. This manifests as choppy, then frozen video playback. The video stream hogs the CPU during this time which can impact audio playback as well.
I updated UncompressedVideoSampleProvider to mark keyframes by setting MFSampleExtension_CleanPoint on the media sample.
During playback of an Ogg file with Theora video in Media Player with in-proc WME, I artificially enabled drop mode on the MF stream under a debugger, and verified that the displayed video frame is periodically updated on keyframes.
=> MSFT: 50159985 - UncompressedVideoSampleProvider is not marking keyframes

.gitmodules, FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/StreamFactory.cpp, FFmpegInterop/packages.config, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/packages.config
We're updating to the latest version of FFmpeg.
- Updated to FFmpeg [7.0](https://github.com/FFmpeg/FFmpeg/releases/tag/n7.0)
-  AV_CODEC_ID_AYUV was [deprecated](https://github.com/FFmpeg/FFmpeg/commit/352799dca8f80b81c37ae3260e424b9479269829) and [removed](https://github.com/FFmpeg/FFmpeg/commit/9ee59b63f5ea37700916815538c32dbcadc4a512)
- Updated packages to the latest versions
- Ogg playback in MediaPlayerCPP
- Ogg playback in Media Player with in-proc WME
- Viewing Ogg file properties in File Explorer with in-proc WME
=> MSFT: 50214245 - Update to FFmpeg 7.0

FFmpegInterop/Utility.h
There's an x86 build break from #315 due to a C4018 (signed/unsigned mismatch) warning in to_cotaskmem_string().
Fixed the warning by casting the int32_t to size_t.
Verified x86 build is successful.
=> MSFT: 21032904 - Fix C4018 (signed/unsigned mismatch) warning in to_cotaskmem_string()

FFmpegConfig.sh, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj.filters, Samples/MediaPlayerCS/MediaPlayerCS.csproj, Tests/UnitTest.csproj
WME uses custom names for its FFmpeg binaries to differentiate them in telemetry. We need to support both the default FFmpeg binary names and WME's custom FFmpeg binary names in the Media Player sample projects.
- Updated the Media Player sample projects to support both default and custom FFmpeg binary names
- We use wildcards to support customizing the FFmpeg binary names, however, wildcards are not supported in project items for .vcxproj files. To workaround this limitation wildcard items are moved to a target body. See [.vcxproj files and wildcards | Microsoft Learn](https://learn.microsoft.com/en-us/cpp/build/reference/vcxproj-files-and-wildcards#move-wildcard-items-to-a-target-body) for more info.
- Removed the /LTCG linker option for FFmpeg builds since it had no effect
I built the …
=> MSFT: 50915398 - Add support for custom FFmpeg binary names

BuildFFmpeg.ps1, FFmpegConfig.sh, FFmpegInterop/FFmpegInterop.vcxproj
In-proc WME binaries have the following BinSkim errors:
- [BA2024.EnableSpectreMitigations](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba2024enablespectremitigations)
- [BA2025.EnableShadowStack](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2025EnableShadowStack)
- Addressed BA2024.EnableSpectreMitigations errors by setting the [/Qspectre](https://learn.microsoft.com/en-us/cpp/build/reference/qspectre) compiler option and linking against the Spectre-mitigated runtime libraries
- vcvars.bat currently uses the wrong path for OneCore Spectre-mitigated libraries. I filed [vcvars.bat uses the wrong path for OneCore Spectre-mitigated libraries - Developer Community (visualstudio.com)](https://developercommunity.visualstudio.com/t/vcvars …
=> MSFT: 49941670 - Enable Spectre mitigations and CET Shadow Stack

FFmpegInterop/FFmpegInterop.vcxproj
FFmpegInterop.dll still has a [BA2024.EnableSpectreMitigations](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba2024enablespectremitigations) BinSkim error after #318, because the SpectreMitigation build property needs to be set before Microsoft.Cpp.props is imported so that the Spectre-mitigated runtime libraries are added to the LIBPATH instead of the default runtime libraries.
Set the SpectreMitigation build property before Microsoft.Cpp.props is imported.
- I ran BinSkim on FFmpegInterop.dll and verified that no errors are reported.
- I validated the following scenarios:
- Ogg playback in MediaPlayerCPP
- Ogg playback in Media Player with in-proc WME
=> MSFT 49941670: Fix Spectre mitigations for FFmpegInterop.dll

FFmpegInterop/FFmpegInterop.vcxproj
The out-of-proc WME build (VC_Target_Library_Platform=Store) is broken after #319 added SpectreMitigation=Spectre due to `LNK1104: cannot open file 'msvcprt.lib'`.
[/Qspectre | Microsoft Learn](https://learn.microsoft.com/en-us/cpp/build/reference/qspectre?view=msvc-170)
> There are no versions of Spectre-mitigated libraries for Universal Windows (UWP) apps or components.
Only set SpectreMitigation=Spectre when VC_Target_Library_Platform=Desktop or VC_Target_Library_Platform=OneCore.
- I verified that both the in-proc WME (VC_Target_Library_Platform=OneCore) and out-of-proc WME (VC_Target_Library_Platform=Store) builds are successful, and no [BA2024.EnableSpectreMitigations](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba2024enablespectremitigations) BinSkim …
=> MSFT: 49941670 - Fix UWP build break due to SpectreMitigation build property

FFmpegInterop/Metadata.h, FFmpegInterop/UncompressedAudioSampleProvider.cpp, FFmpegInterop/UncompressedVideoSampleProvider.cpp
I'm writing some new internal WME tests that found a few minor issues.
- Fix the property key type for PKEY_Music_Genre
- Set [MF_MT_COMPRESSED](https://learn.microsoft.com/en-us/windows/win32/medfound/mf-mt-all-samples-independent-attribute) = true for uncompressed audio/video streams
- This was supposed to already be set for uncompressed video by VideoEncodingProperties::CreateUncompressed(), however, it was getting overwritten and set to false by SampleProvider::SetEncodingProperties().
- Set [MF_MT_ALL_SAMPLES_INDEPENDENT](https://learn.microsoft.com/en-us/windows/win32/medfound/mf-mt-all-samples-independent-attribute) = false for uncompressed video streams 
- We don't need to explicitly set this for uncompressed audio streams since it's set by AudioEncodingProperties::CreatePcm().
I …
=> MSFT: 21032904 - Fix the property key type for PKEY_Music_Genre

FFmpegInterop/ACMSampleProvider.cpp, FFmpegInterop/BitstreamReader.cpp, FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/FFmpegInteropBuffer.cpp, FFmpegInterop/FFmpegInteropByteStreamHandler.cpp, FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/Metadata.cpp, FFmpegInterop/UncompressedAudioSampleProvider.cpp, FFmpegInterop/UncompressedVideoSampleProvider.cpp, FFmpegInterop/Utility.h, FFmpegInterop/VFWSampleProvider.cpp, FFmpegInterop/dllmain.cpp, FFmpegInterop/pch.h
I've been bitten twice by build breaks due to [C4018 (signed/unsigned mismatch)](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=msvc-170) warnings that repro'd for x86 but not x64 (#308 and #316). It turns out that for the x64 build the warnings being generated were [C4388 (signed/unsigned mismatch)](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4388?view=msvc-170) which is a level 4, off by default warning.
We want to follow [best practices](https://learn.microsoft.com/en-us/cpp/code-quality/build-reliable-secure-programs?view=msvc-170#23-code-based-or-static-analysis) and enable level 4 warnings.
- Enabled level 4 warnings (`/W4`)
- Enabled [C4388 (signed/unsigned …
=> MSFT: 50731161 - Enable level 4 warnings

BuildFFmpeg.ps1
I fixed the [bug](https://developercommunity.visualstudio.com/t/vcvarsbat-uses-the-wrong-path-for-OneCo/10664642) with vcvars.bat using the wrong path for OneCore spectre-mitigated libraries, and the fix was released in VS 2022 version 17.11.
I removed the workaround in BuildFFmpeg.ps1 for vcvars.bat using the wrong path for OneCore spectre-mitigated libraries.
I verified BuildFFmpeg.ps1 with `-AppPlatform onecore` worked in the following scenarios:
- A local FFmpeg build with VS 2022 version 17.11.4
- An in-proc WME ADO buddy build with VS 2022 version 17.11.3
=> MSFT: 53265203 - Remove the workaround in BuildFFmpeg.ps1 for vcvars.bat using the wrong path for OneCore spectre-mitigated libs

.gitmodules, FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/packages.config, Samples/MediaPlayerCPP/MediaPlayerCPP.vcxproj, Samples/MediaPlayerCPP/packages.config, Tests/UnitTest.csproj
We're updating to the latest version of FFmpeg.
- Updated to FFmpeg [7.1](https://github.com/FFmpeg/FFmpeg/releases/tag/n7.1)
- Updated NuGet packages to the latest versions
- Ogg playback in MediaPlayerCPP
- Ogg playback in Media Player with in-proc WME and out-of-proc WME
- Internal Ogg unit tests with in-proc WME and out-of-proc WME
=> MSFT: 54857258 - Update to FFmpeg 7.1

FFmpegInterop/FFmpegInteropMSS.cpp, FFmpegInterop/Utility.h
When a file stream read/seek fails, FileStreamRead()/FileStreamSeek() currently return AVERROR_EXTERNAL. This propagates up the call stack and gets converted to E_FAIL by averror_to_hresult() since there is no explicit mapping for it.
We want to propagate the failed HRESULT that occurred instead so that we can provide a more specific error/message to the app/user.
 
- I updated FileStreamRead()/FileStreamSeek() to return the failed HRESULT instead of AVERROR_EXTERNAL when a file stream read/seek fails.
- In order to detect that the status returned by FFmpeg is an HRESULT and not an unmapped AVERROR, I updated averror_to_hresult() to assume that the status is an HRESULT if it's in WIL's thread error cache. See [Internals Local data - Thread-local data · microsoft/wil …
=> MSFT: 55143016 - Propagate the HRESULT for file stream read/seek failures

BuildFFmpeg.ps1, FFmpegConfig.sh, FFmpegInterop/FFmpegInterop.vcxproj, FFmpegInterop/VFWSampleProvider.cpp
To create fuzzers for WME (Ogg, Theora, Vorbis), which rely on FFmpeg, we need to be able to build FFmpeg with ASAN and SanCov enabled
To enable fuzzing, we need to add the compiler flags "/fsanitize=address /fsanitize-coverage=inline-8bit-counters /fsanitize-coverage=edge /fsanitize-coverage=trace-cmp /fsanitize-coverage=trace-div" and link to either sancov.lib (dynamic CRT, /MD) or libsancov.lib (static CRT, /MT). The libraries are located in $VCToolsInstallDir\lib\\$arch, which is dependent upon the Visual Studio installation of the building machine. Fuzzing documentation can be found [here](https://eng.ms/docs/cloud-ai-platform/azure-edge-platform-aep/aep-security/epsf-edge-and-platform-security-fundamentals/the-onefuzz-service/onefuzz/faq/notwindows/walkthrough).
I added a fuzzing …
=> Add fuzzing flag to FFmpeg build scripts to build FFmpeg with ASAN and SanCov enabled

FFmpegInterop/FFmpegInterop.vcxproj
**Why is this change being made?**
The Platform macro resolved to Win32 in cases I assumed it would be set to x86. This caused the ASAN library include path to be incorrect, and the building FFmpegInterop with fuzzing for x86 to fail.
**What changed?**
Changed the ASAN library include path to use PlatformTarget instead of Platform, which resolves to x86 instead of Win32. The path for the FFmpeg Build libraries also uses PlatformTarget in line 91.
Changed another condition that was checking if Platform equaled x86 to also check if Platform equals Win32, as these are essentially the same condition.
**How was the change tested?**
Built FFmpegInterop for all architectures with and without fuzzing (excluding arm64 for fuzzing) using this branch via the WME pipeline.
=> Fix directory path for fuzzing libraries
